### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by rinzlerFix** [pena-ara/Nmenu#1]
I've installed nmenu but all the icons are missing, how can I fix it? Do I need certain icon pack or font? If so can I change it to another?
I'm new to the linux so sorry if this is a dumb question or the wrong place to put it.
![nmenu](https://user-images.githubusercontent.com/54543087/97631059-56ab1a00-1a28-11eb-9d79-72be7738a067.jpg)

The screenshot is blurred because the menu was closing when the shot was taken but I think it's possible to see the issue.

**Comment by pena-ara** [comment]
u can install font powerline or nerd font :)
